on:
  push:
    branches:
      - feat/basic-diff

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      actions: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0

      - uses: Arbeidstilsynet/action-check-changes@feat/basic-diff
        id: changes
        with:
          base-ref: origin/main
          include: |
            .
          exclude: |
            README.md

      - run: |
          echo "Changed: ${{ steps.changes.outputs.changes_detected }}"
          echo "Base SHA: ${{ steps.changes.outputs.base_sha }}"
          echo "Head SHA: ${{ steps.changes.outputs.head_sha }}"
          echo "Changed files: ${{ steps.changes.outputs.changed_files }}"
