on:
  push:
    branches:
      - feat/basic-diff

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      actions: read
    outputs:
      changed: ${{ steps.changes.outputs.changes_detected }}
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          fetch-depth: 0

      - uses: "./"
        id: changes
        with:
          workflow-file: "test.yml"
          include: .github/workflows/
          exclude: |
            .github/workflows/test-basic.yml
            README.md
            somefile

      - run: |
          echo "Changed: ${{ steps.changes.outputs.changes_detected }}"
          echo "Base SHA: ${{ steps.changes.outputs.base_sha }}"
          echo "Head SHA: ${{ steps.changes.outputs.head_sha }}"
          echo "Changed files: ${{ steps.changes.outputs.changed_files }}"

  deploy:
    needs: check
    if: needs.check.outputs.changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

      - run: echo "insert deploy here"
